const translations = {
    en: {
        'restaurant-name': 'Welcome to Our Restaurant',
        'menu-title': 'Menu',
        'item1-name': 'Margherita Pizza',
        'item1-desc': 'Classic pizza with tomato sauce, mozzarella, and basil.',
        'item1-price': '$12.99',
        'item2-name': 'Pepperoni Pizza',
        'item2-desc': 'Pizza topped with pepperoni and cheese.',
        'item2-price': '$14.99',
        'item3-name': 'Spaghetti Carbonara',
        'item3-desc': 'Pasta with eggs, cheese, pancetta, and black pepper.',
        'item3-price': '$11.99',
        'item4-name': 'Lasagna',
        'item4-desc': 'Layered pasta with meat sauce and cheese.',
        'item4-price': '$13.99',
        'item5-name': 'Caesar Salad',
        'item5-desc': 'Romaine lettuce with Caesar dressing, croutons, and parmesan.',
        'item5-price': '$9.99',
        'item6-name': 'Grilled Chicken',
        'item6-desc': 'Juicy grilled chicken breast with herbs.',
        'item6-price': '$15.99',
        'item7-name': 'Fish and Chips',
        'item7-desc': 'Fried fish with crispy chips.',
        'item7-price': '$16.99',
        'item8-name': 'Tiramisu',
        'item8-desc': 'Classic Italian dessert with coffee and mascarpone.',
        'item8-price': '$7.99',
        'item9-name': 'Gelato',
        'item9-desc': 'Italian ice cream in various flavors.',
        'item9-price': '$5.99',
        'item10-name': 'Espresso',
        'item10-desc': 'Strong Italian coffee.',
        'item10-price': '$3.99',
        'item11-name': 'Caprese Salad',
        'item11-desc': 'Tomatoes, mozzarella, and basil with olive oil.',
        'item11-price': '$10.99',
        'item12-name': 'Risotto',
        'item12-desc': 'Creamy rice dish with mushrooms.',
        'item12-price': '$12.99',
        'item13-name': 'Bruschetta',
        'item13-desc': 'Toasted bread with tomato and basil.',
        'item13-price': '$8.99',
        'item14-name': 'Panna Cotta',
        'item14-desc': 'Vanilla custard with berry sauce.',
        'item14-price': '$6.99',
        'item15-name': 'Mineral Water',
        'item15-desc': 'Sparkling or still water.',
        'item15-price': '$2.99',
        'footer-text': 'Thank you for visiting our restaurant!'
    },
    ru: {
        'restaurant-name': 'Добро пожаловать в наш ресторан',
        'menu-title': 'Меню',
        'item1-name': 'Маргарита Пицца',
        'item1-desc': 'Классическая пицца с томатным соусом, моцареллой и базиликом.',
        'item1-price': '12.99 $',
        'item2-name': 'Пепперони Пицца',
        'item2-desc': 'Пицца с пепперони и сыром.',
        'item2-price': '14.99 $',
        'item3-name': 'Спагетти Карбонара',
        'item3-desc': 'Паста с яйцами, сыром, панчеттой и черным перцем.',
        'item3-price': '11.99 $',
        'item4-name': 'Лазанья',
        'item4-desc': 'Слоеная паста с мясным соусом и сыром.',
        'item4-price': '13.99 $',
        'item5-name': 'Салат Цезарь',
        'item5-desc': 'Ромэн с соусом Цезарь, гренками и пармезаном.',
        'item5-price': '9.99 $',
        'item6-name': 'Гриль Курица',
        'item6-desc': 'Сочная куриная грудка на гриле с травами.',
        'item6-price': '15.99 $',
        'item7-name': 'Рыба и Чипсы',
        'item7-desc': 'Жареная рыба с хрустящими чипсами.',
        'item7-price': '16.99 $',
        'item8-name': 'Тирамису',
        'item8-desc': 'Классический итальянский десерт с кофе и маскарпоне.',
        'item8-price': '7.99 $',
        'item9-name': 'Джелато',
        'item9-desc': 'Итальянское мороженое различных вкусов.',
        'item9-price': '5.99 $',
        'item10-name': 'Эспрессо',
        'item10-desc': 'Крепкий итальянский кофе.',
        'item10-price': '3.99 $',
        'item11-name': 'Салат Капрезе',
        'item11-desc': 'Помидоры, моцарелла и базилик с оливковым маслом.',
        'item11-price': '10.99 $',
        'item12-name': 'Ризотто',
        'item12-desc': 'Кремовое блюдо из риса с грибами.',
        'item12-price': '12.99 $',
        'item13-name': 'Брускетта',
        'item13-desc': 'Поджаренный хлеб с томатами и базиликом.',
        'item13-price': '8.99 $',
        'item14-name': 'Панна Котта',
        'item14-desc': 'Ванильный крем с ягодным соусом.',
        'item14-price': '6.99 $',
        'item15-name': 'Минеральная Вода',
        'item15-desc': 'Газированная или негазированная вода.',
        'item15-price': '2.99 $',
        'footer-text': 'Спасибо за посещение нашего ресторана!'
    },
    zh: {
        'restaurant-name': '欢迎来到我们的餐厅',
        'menu-title': '菜单',
        'item1-name': '玛格丽塔披萨',
        'item1-desc': '经典披萨配番茄酱、马苏里拉奶酪和罗勒。',
        'item1-price': '12.99 美元',
        'item2-name': '意大利辣香肠披萨',
        'item2-desc': '配意大利辣香肠和奶酪的披萨。',
        'item2-price': '14.99 美元',
        'item3-name': '卡博纳拉意大利面',
        'item3-desc': '配鸡蛋、奶酪、培根和黑胡椒的面条。',
        'item3-price': '11.99 美元',
        'item4-name': '千层面',
        'item4-desc': '分层面条配肉酱和奶酪。',
        'item4-price': '13.99 美元',
        'item5-name': '凯撒沙拉',
        'item5-desc': '罗马生菜配凯撒酱、面包丁和帕尔马干酪。',
        'item5-price': '9.99 美元',
        'item6-name': '烤鸡肉',
        'item6-desc': '多汁的烤鸡胸肉配香草。',
        'item6-price': '15.99 美元',
        'item7-name': '炸鱼薯条',
        'item7-desc': '炸鱼配脆薯条。',
        'item7-price': '16.99 美元',
        'item8-name': '提拉米苏',
        'item8-desc': '经典意大利甜点配咖啡和马斯卡彭奶酪。',
        'item8-price': '7.99 美元',
        'item9-name': '意大利冰淇淋',
        'item9-desc': '各种口味的意大利冰淇淋。',
        'item9-price': '5.99 美元',
        'item10-name': '浓缩咖啡',
        'item10-desc': '浓郁的意大利咖啡。',
        'item10-price': '3.99 美元',
        'item11-name': '卡普雷塞沙拉',
        'item11-desc': '番茄、马苏里拉奶酪和罗勒配橄榄油。',
        'item11-price': '10.99 美元',
        'item12-name': '烩饭',
        'item12-desc': '奶油蘑菇米饭。',
        'item12-price': '12.99 美元',
        'item13-name': '布鲁斯凯塔',
        'item13-desc': '烤面包配番茄和罗勒。',
        'item13-price': '8.99 美元',
        'item14-name': '潘纳科塔',
        'item14-desc': '香草奶油配浆果酱。',
        'item14-price': '6.99 美元',
        'item15-name': '矿泉水',
        'item15-desc': '气泡水或静止水。',
        'item15-price': '2.99 美元',
        'footer-text': '感谢您光临我们的餐厅！'
    }
};

function changeLanguage(lang) {
    const elements = document.querySelectorAll('[id]');
    elements.forEach(element => {
        const id = element.id;
        if (translations[lang] && translations[lang][id]) {
            element.innerHTML = translations[lang][id];
        }
    });
}